# inflator.toml syntax documentation: https://github.com/inflated-goboscript/inflator#inflator
name = "datetime"
version = "v0.0.0"
username = "inflated-goboscript"

[dependencies]
time = "time"
string = "string"
assert = "assert"
math = "math"